### PR TITLE
Add example for reduks

### PR DESCRIPTION
**Pull request by kittinunf**
I add 2 simple examples for Reduks.

`example/counter` - It is a command line app, to demonstrate counter app with reduks. It is meant to be really simple, accepting simple commands, ie. i (increment), d (decrement), s(show), q(quit). 

It is a command line app. You could run it by using `./gradlew run`

`example/counter-android` - This is pretty much the same spirit with Android UI, use increment/decrement to alter counter state. 

Here is ss for this simple Android app. 

screen shot 2016-09-02 at 5 53 39 pm

Bundled together I have updated minor details like Android build tool version and support version.

I want to start with something utterly simple. So, counter example is an ideal choice. And for every redux implementation, counter example seems to be compulsory. I take one to create it for Reduks repo.

PS. I am not sure what to do with `examples/` folder so I leave it as it is. I don't want to delete stuff in other ppl repo. So, you might wanna do sth about it.

### CODE REVIEW

**Comment by beyondeye** [comment]
Hi! thanks a lot! The travis ci build is failing because of some lint checks.
:examples:lint FAILED 
Can you have a look at it, when you can?
I will be happy to merge the PR then

**Comment by kittinunf** [comment]
Sure. I am catching a flight back to BKK. So I will go offline for a bit while. Let me get back to you when I landed.

**Comment by kittinunf** [comment]
It fails under reduks-logger. Could you please help me fix it?

reduks-logger:testDebugUnitTest FAILED

**Comment by beyondeye** [comment]
Sure

**Pull request merged**
